### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by LuckyHouse** [minhhoangbui/lightweight_openpose_tensorflow#3]
This is my configuration,but still OOM (GTX 1660 6G).
Is there any way to reduce model parameters.
I don't need extra precision

> 
> MODEL:
>   num_channels:  8 #128
>   num_stages: 1
>   input_size: 256 #368
> TRAIN:
>   num_epochs: 40
>   learning_rate: 0.000005
>   decay_step: 5000
>   decay_rate: 0.96
>   batch_size: 1
> VAL:
>   batch_size: 1

**Comment by minhhoangbui** [comment]
I'm sorry
It seems to me that you need at least 7gb to load the model. There are no way around
